services:

  gateway:
    build:
      context: ./gateway
      dockerfile: ../Dockerfile_services
    ports:
      - "9000:9000"
    command: java -Dspring.profiles.active="docker" -jar target/gateway-0.0.1-SNAPSHOT.jar
    networks:
      - services
      - default
    depends_on:
      - bar-service
      - foo-service

  eureka:
    build:
      context: ./eureka
      dockerfile: ../Dockerfile_services
    ports:
      - "9999:9999"
    command: java -jar -Dspring.profiles.active="docker" target/eureka-0.0.1-SNAPSHOT.jar
    networks:
      - services

  bar-service:
    build:
      context: ./bar-service
      dockerfile: ../Dockerfile_services
    ports:
      - "9020:9020"
    command: java -jar -Dspring.profiles.active="docker" target/bar-service-0.0.1-SNAPSHOT.jar
    networks:
      - services
    depends_on:
      - eureka

  foo-service:
    build:
      context: ./foo-service
      dockerfile: ../Dockerfile_services
    ports:
      - "9010:9010"
    command: java -jar -Dspring.profiles.active="docker" target/foo-service-0.0.1-SNAPSHOT.jar
    networks:
      - services
    depends_on:
      - eureka

networks:
  services:
    driver: bridge