spring:
  application:
    name: eureka-server

server:
  port: 9999

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka